export const TYPE = {
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_CONFIRM_MODAL: 'OPEN_CONFIRM_MODAL',
  CLOSE_CONFIRM_MODAL: 'CLOSE_CONFIRM_MODAL',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  SET_POSTS: 'SET_POSTS',
};
