import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import './_styles/_css/common.scss';
import './_styles/_css/reset.scss';
import './_styles/_css/component.scss';
import SmoothScroll from './SmoothScroll';
import { useEffect } from 'react';
import Root from './_components/root';
import ReduxProvider from './provider';

const geistSans = localFont({
  src: './_fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './_fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Kjiyu-devlog',
  description: 'Generated by create next app/node.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Root>{children}</Root>
        </ReduxProvider>
      </body>
    </html>
  );
}
